// ─── Landing Page Content ─────────────────────────────────────────────────────
// All copy, labels, and data for the landing page live here.
// Update this file whenever you need to change text, prices, or feature lists.

const R2 = "https://pub-425a4c402193444fb20eeb6725aa6557.r2.dev/videos";

// ─── Site ─────────────────────────────────────────────────────────────────────

export const SITE = {
  name: "ReelForge",
  tagline: "AI Short-Form Video Content Machine",
  url: process.env.NEXT_PUBLIC_APP_URL ?? "https://aireelforge.com",
};

// ─── Nav ──────────────────────────────────────────────────────────────────────

export const NAV_LINKS = [
  { label: "How it Works", href: "#pipeline" },
  { label: "Styles", href: "#styles" },
  { label: "Pricing", href: "#pricing" },
  { label: "FAQ", href: "#faq" },
] as const;

export const NAV_CTA = {
  signIn: "Sign in",
  primary: { label: "Start for $5", href: "/sign-up" },
};

// ─── Hero ─────────────────────────────────────────────────────────────────────

export const HERO = {
  eyebrow: "7 videos. Auto-posted. You approved once.",
  headlineLine1: "Your Content Channel,",
  headlineLine2: "On Autopilot.",
  subheadline:
    "Plan a full week of short-form videos in 10 minutes. ReelForge writes every script, generates every AI video, and posts them automatically — while you're doing anything else.",
  primaryCta: {
    label: "Start Your First Week — $5",
    subtext: "7 video credits · No subscription required",
    href: "/sign-up",
  },
  secondaryCta: {
    label: "Watch how it works (90 sec)",
  },
  proof: {
    text: "Joined by creators finally sleeping on Sundays",
    rating: "5.0 from early creators",
  },
};

// ─── Video Showcase ───────────────────────────────────────────────────────────

export const SHOWCASE = {
  label: "Built with ReelForge",
  headline: "Real videos. Real niches.\nZero editing.",
  subheadline:
    "Every video below was generated by ReelForge — scripted by Claude AI, visuals built scene by scene with Grok, assembled automatically and ready to post.",
  videos: [
    {
      style: "Cinematic",
      niche: "Personal Finance",
      platform: "TikTok",
      views: "2.4M views",
      hook: "3 money habits that changed everything",
      gradientFrom: "#0f172a",
      gradientTo: "#1e3a5f",
      accentColor: "#4a90e2",
      videoUrl: `${R2}/Cinematic.mp4`,
    },
    {
      style: "UGC",
      niche: "Daily Routine",
      platform: "Instagram",
      views: "890K views",
      hook: "The morning that made me $10k",
      gradientFrom: "#1a0a05",
      gradientTo: "#3d1a0a",
      accentColor: "#f55c2a",
      videoUrl: `${R2}/daily-routine.mp4`,
    },
    {
      style: "Tutorial",
      niche: "AI & Tech",
      platform: "YouTube Shorts",
      views: "1.1M views",
      hook: "5 AI tools you probably don't know about",
      gradientFrom: "#0d0d1a",
      gradientTo: "#1a1040",
      accentColor: "#a78bfa",
      videoUrl: `${R2}/learn ai.mp4`,
    },
    {
      style: "Story",
      niche: "Career Growth",
      platform: "TikTok",
      views: "3.2M views",
      hook: "The interview mistake that cost me the job",
      gradientFrom: "#0f1a0a",
      gradientTo: "#1e3d10",
      accentColor: "#34d399",
      videoUrl: `${R2}/interview mistake.mp4`,
    },
    {
      style: "Cinematic",
      niche: "Fact Check",
      platform: "YouTube Shorts",
      views: "560K views",
      hook: "Claude got this completely wrong — here's why",
      gradientFrom: "#1a1500",
      gradientTo: "#3d3000",
      accentColor: "#fbbf24",
      videoUrl: `${R2}/claude wrong.mp4`,
    },
    {
      style: "UGC",
      niche: "Fitness",
      platform: "Instagram",
      views: "1.8M views",
      hook: "Why you're not losing weight (honest answer)",
      gradientFrom: "#001a1a",
      gradientTo: "#003d3d",
      accentColor: "#2dd4bf",
      videoUrl: `${R2}/createdbyreelforge.mp4`,
    },
    {
      style: "Tutorial",
      niche: "Business",
      platform: "TikTok",
      views: "420K views",
      hook: "How to scale your idea to $10k/month",
      gradientFrom: "#0a1a2e",
      gradientTo: "#1a2e4a",
      accentColor: "#4a90e2",
      videoUrl: `${R2}/learn ai.mp4`,
    },
    {
      style: "Cinematic",
      niche: "Self-Improvement",
      platform: "Instagram",
      views: "2.1M views",
      hook: "Stop caring what people think — here's how",
      gradientFrom: "#1a1a1a",
      gradientTo: "#2a2a2a",
      accentColor: "#f4f4f8",
      videoUrl: `${R2}/daily-routine.mp4`,
    },
    {
      style: "Story",
      niche: "Mindset",
      platform: "YouTube Shorts",
      views: "1.5M views",
      hook: "The habit that separates winners from everyone else",
      gradientFrom: "#1a1505",
      gradientTo: "#2a200a",
      accentColor: "#fbbf24",
      videoUrl: `${R2}/createdbyreelforge.mp4`,
    },
    {
      style: "UGC",
      niche: "Creator Economy",
      platform: "TikTok",
      views: "950K views",
      hook: "I automated my entire content channel. Here's how.",
      gradientFrom: "#1a051a",
      gradientTo: "#2a0a2a",
      accentColor: "#a78bfa",
      videoUrl: `${R2}/Cinematic.mp4`,
    },
    {
      style: "Tutorial",
      niche: "Real Estate",
      platform: "Instagram",
      views: "670K views",
      hook: "3 mistakes that kill first-time buyers",
      gradientFrom: "#051a05",
      gradientTo: "#0a2a0a",
      accentColor: "#34d399",
      videoUrl: `${R2}/interview mistake.mp4`,
    },
    {
      style: "Cinematic",
      niche: "History",
      platform: "YouTube Shorts",
      views: "4.5M views",
      hook: "The truth about the Roman Empire nobody tells you",
      gradientFrom: "#1a0505",
      gradientTo: "#2a0a0a",
      accentColor: "#f87171",
      videoUrl: `${R2}/createdbyreelforge.mp4`,
    },
  ],
};

// ─── Proof Strip ──────────────────────────────────────────────────────────────

export const PROOF_STATS = [
  { value: "7", label: "Videos planned\nin 10 minutes" },
  { value: "~0", label: "Minutes of editing\never required" },
  { value: "Auto", label: "Posts to your channels\nwhile you sleep" },
  { value: "1", label: "Approval click\nfor the whole week" },
] as const;

// ─── Problem ──────────────────────────────────────────────────────────────────

export const PROBLEM = {
  label: "The real cost of doing it manually",
  headlineLine1: "The algorithm wants daily content.",
  headlineLine2: "You have",
  headlineAccent: "a life.",
  body: [
    "Every day without a post is a day the algorithm buries you. But making a video worth watching takes 2–4 hours — scripting, recording, editing, captioning, scheduling.",
    "Most creators burn out by month two. Not because they ran out of ideas. Because they ran out of energy.",
    "The channels still growing? They stopped doing it by hand.",
  ],
  cards: [
    {
      iconKey: "clock",
      title: "2–4 hours. Every single day.",
      body: "That's not a content strategy. That's a second job you didn't sign up for. And the moment you miss a day, the algorithm makes you pay for it.",
    },
    {
      iconKey: "trending-down",
      title: "Consistency is the whole game.",
      body: "Skip 3 days and lose 3 weeks of momentum. The algorithm doesn't care that you were sick, busy, or just human. It only rewards the ones who show up — every day, without fail.",
    },
    {
      iconKey: "flame",
      title: "Burnout is the real enemy.",
      body: "You started to create because you love it. Somewhere around the fifteenth edit of the week, that love becomes obligation. Obligation becomes resentment. And then you go quiet.",
    },
  ],
};

// ─── Solution Reveal ──────────────────────────────────────────────────────────

export const SOLUTION = {
  headlineLine1: "You don't have a content problem.",
  headlineLine2: "You have a time problem.",
  body: [
    "What if Sunday night you spent 10 minutes reviewing a week of video ideas — and by Monday morning, the first one was already live on your channels?",
    "No scripting. No recording. No editing. No scheduling. No checking. Just... done.",
  ],
  closer: "That's not a dream. That's ReelForge.",
  pipelineNodes: ["Your Brand", "AI Week Plan", "One Approval", "Auto-Generated", "Auto-Posted"],
  inlineCta: { label: "See the full pipeline", href: "#pipeline" },
};

// ─── Pipeline ─────────────────────────────────────────────────────────────────

export const PIPELINE = {
  label: "The ReelForge Pipeline",
  headlineLine1: "One approval Sunday.",
  headlineLine2: "Seven posts all week.",
  subheadline:
    "Five steps. Under 10 minutes of your attention. Everything else runs itself.",
  steps: [
    {
      num: "01",
      title: "Set your brand once. Use it forever.",
      body: "Connect your social accounts. Tell ReelForge your niche, your tone, your visual style. We build your AI brand character — a consistent visual identity that appears in every scene of every video, every single week. Set it once. Never think about it again.",
    },
    {
      num: "02",
      title: "Claude plans your entire content week.",
      body: "Hit 'New Plan.' In under 2 minutes, Claude returns a full 7-day calendar — hooks, angles, formats, and script outlines for every slot. Not generic filler. Content built specifically for your brand, your niche, and what your audience actually wants to watch.",
      pill: "Full week planned in under 2 minutes",
      pillVariant: "primary" as const,
    },
    {
      num: "03",
      title: "Edit anything. Then approve with one click.",
      body: "Swap a topic. Rewrite a hook. Change the format. Or just read through and hit Approve. You're the editor-in-chief — not the production crew. Most people change nothing. Some tweak a few titles. The choice is always yours.",
      pill: "Most users approve in under 3 minutes",
      pillVariant: "primary" as const,
    },
    {
      num: "04",
      title: "Every video generates while you sleep.",
      body: "After approval, our operator runs the pipeline in the background — writing full scripts, generating every scene with AI visuals, assembling the final MP4 with subtitles burned in. All 7 videos. In parallel. You don't watch. You don't wait. You just check in later.",
      pill: "7 videos generated automatically",
      pillVariant: "primary" as const,
    },
    {
      num: "05",
      title: "Posts itself. You just check the results.",
      body: "Choose how you want to publish: auto-schedule at peak times, save as drafts for your own review, or download the MP4s. Your videos go live exactly when they should. The algorithm sees consistency. Your audience sees content. You see growth — without the grind.",
      pill: "Autopilot from approval to publish",
      pillVariant: "success" as const,
    },
  ],
};

// ─── Visual Styles ────────────────────────────────────────────────────────────

export const STYLES = {
  label: "Choose your look",
  headlineLine1: "7 visual styles.",
  headlineLine2: "4 subtitle styles.",
  headlineAccent: "Zero compromises.",
  subheadline:
    "Set your visual style once per brand. Every scene of every video — for every week — follows it automatically.",

  visualStyles: [
    {
      iconKey: "film",
      iconBg: "rgba(91,141,239,0.12)",
      iconColor: "var(--accent-secondary)",
      name: "Cinematic",
      mood: "Photorealistic · Immersive · Documentary feel",
      description:
        "Real-world photography, cinematic composition. Your script becomes a narrative — each scene a carefully composed shot. Looks like a Netflix short, costs nothing like one.",
    },
    {
      iconKey: "smile",
      iconBg: "rgba(251,191,36,0.12)",
      iconColor: "var(--accent-warning)",
      name: "Cartoon",
      mood: "2D flat · Expressive · Impossible to scroll past",
      description:
        "Bold outlines, saturated colors, exaggerated expressions. Built for niches that need to entertain before they can educate. The algorithm loves it.",
    },
    {
      iconKey: "star",
      iconBg: "rgba(52,211,153,0.12)",
      iconColor: "var(--accent-success)",
      name: "Mascot",
      mood: "3D character · Brand identity · Instantly recognizable",
      description:
        "Your topic becomes a 3D cartoon character — a talking coin for finance, an egg for nutrition. Built for channels building a recognizable identity that viewers remember.",
    },
    {
      iconKey: "shapes",
      iconBg: "rgba(245,92,42,0.12)",
      iconColor: "var(--accent-primary)",
      name: "2D Animation",
      mood: "Clean · Explainer · Vector-style",
      description:
        "Flat vector illustration. Icons, geometric shapes, bold diagrams. No characters — pure visual storytelling through shapes. The go-to for educational content that converts.",
    },
    {
      iconKey: "zap",
      iconBg: "rgba(248,113,113,0.12)",
      iconColor: "var(--accent-danger)",
      name: "Motion Graphics",
      mood: "Kinetic · High-energy · Data-driven",
      description:
        "Stats, facts, bold claims — each one a graphic reveal. Ultra-fast pacing designed to stop the scroll before the first second is over.",
    },
    {
      iconKey: "pen-line",
      iconBg: "rgba(255,255,255,0.06)",
      iconColor: "var(--text-secondary)",
      name: "Whiteboard",
      mood: "Tutorial · Step-by-step · Deeply trusted",
      description:
        "Hand-drawn visuals that build as the narration explains. The classic format viewers trust for learning complex things simply — and sharing with friends.",
    },
    {
      iconKey: "video",
      iconBg: "rgba(91,141,239,0.08)",
      iconColor: "var(--accent-secondary)",
      name: "Stock Footage",
      mood: "Professional · Polished · Brand-ready",
      description:
        "Warm, real-world visuals that feel like established brand content. For creators who want to look like they've been at this for years — even if they just started.",
    },
  ],

  subtitleStyles: [
    {
      name: "Bold Pop",
      badge: "Most Popular",
      badgeVariant: "warning" as const,
      description:
        "Large center-screen text with the active word highlighted. Impossible to miss. Built for fast, high-energy content where every word needs to land.",
    },
    {
      name: "Word Highlight",
      badge: "Most Engaging",
      badgeVariant: "primary" as const,
      description:
        "Each word scales into frame at its exact timestamp. Hypnotic and precise. Best when every single word carries weight — and you need viewers to feel it.",
    },
    {
      name: "Minimal",
      badge: "Clean",
      badgeVariant: "muted" as const,
      description:
        "Unobtrusive sentence-level text at the bottom third. For creators who don't want subtitles competing with their visuals — just quietly serving the 85% watching on mute.",
    },
    {
      name: "Cinematic",
      badge: "Premium Feel",
      badgeVariant: "secondary" as const,
      description:
        "Film-style subtitle band. Borrowed from documentary aesthetics. Makes even the simplest content feel like it belongs on a streaming platform.",
    },
  ],
};

// ─── Before / After ───────────────────────────────────────────────────────────

export const COMPARISON = {
  withoutLabel: "Without ReelForge",
  withLabel: "With ReelForge",
  without: [
    "2–4 hours per video, every single day",
    "Blank page every morning — scripting from zero",
    "Manual recording, editing, exporting, captioning",
    "Posting gaps every time life gets in the way",
    "Algorithm punishes every missed day — ruthlessly",
    "Hiring editors or VAs just to keep pace",
    "Planning content in your head at midnight",
    "Burning out and going quiet for weeks at a time",
  ],
  with: [
    "10 minutes on Sunday. Your whole week is done.",
    "Claude writes every script — hook, body, CTA included",
    "AI generates every scene, assembles every MP4",
    "Posts go live whether you're working or on holiday",
    "Consistent presence, without consistent effort",
    "No team needed — one tool runs the whole machine",
    "A full week of content visible before it's made",
    "The kind of output that used to require a studio",
  ],
  cta: {
    headline: "You already know which side you want to be on.",
    label: "Start for $5 → Your first week",
    subtext: "7 video credits · No monthly commitment · Takes 10 minutes",
    href: "/sign-up",
  },
};

// ─── Pricing ──────────────────────────────────────────────────────────────────

export const PRICING = {
  label: "Founding Member Pricing",
  headlineLine1: "Start for $5.",
  headlineLine2: "See your first week live.",
  subheadline:
    "7 video credits. A complete week of content. See a finished video live on your channel — then decide.",
  urgencyBanner:
    "Founding member pricing — subscription rates are locked in for life when you join during launch.",
  urgencyNote: "Rates increase after launch period ends.",
  monthlyNote: "All subscriptions billed monthly. Cancel any time.",
  footerNote:
    "All plans: 1080×1920 MP4 · Subtitles burned in · Auto-post to social channels · Video library included",
  plans: [
    {
      name: "Try Out",
      nameStyle: "muted" as const,
      price: "$5",
      period: "one time",
      subPrice: "One full week. No strings attached.",
      features: [
        "7 video credits — a complete week",
        "AI-generated week plan",
        "Auto-post to social channels",
        "Full visual style library",
        "Download your MP4s anytime",
      ],
      cta: "Try it for $5",
      href: "/sign-up",
      highlighted: false,
    },
    {
      name: "Starter",
      nameStyle: "muted" as const,
      price: "$49",
      period: "/ month",
      subPrice: "1 video/day · 30 videos/month · ~$1.63 each",
      features: [
        "1 video per day, every day",
        "30 videos per month",
        "Unlimited week plans",
        "Auto-schedule or save as drafts",
        "Email when your videos are ready",
      ],
      cta: "Start Starter Plan",
      href: "/sign-up",
      highlighted: false,
    },
    {
      name: "Pro",
      nameStyle: "accent" as const,
      price: "$99",
      period: "/ month",
      subPrice: "3 videos/day · 90 videos/month · ~$1.10 each",
      features: [
        "3 videos per day — maximum consistency",
        "90 videos per month",
        "Everything in Starter",
        "Priority generation queue",
        "Multiple brand profiles",
      ],
      cta: "Go Pro",
      href: "/sign-up",
      highlighted: true,
      badge: "Most Popular",
    },
  ],
};

// ─── FAQ ──────────────────────────────────────────────────────────────────────

export const FAQ = {
  label: "Common Questions",
  headline: "Honest answers.",
  items: [
    {
      question: "Do I need to be online while my videos generate?",
      answer:
        "No — and that's the entire point. Once you approve your week plan, the pipeline runs completely in the background. Scripts get written, scenes get generated, MP4s get assembled. You could be asleep, at the gym, or on a flight. When your videos are ready, you get a notification. You don't babysit anything.",
    },
    {
      question: "Will the content actually sound and look like my brand?",
      answer:
        "Yes. During setup you define your niche, tone, and visual style — and we build your AI brand character, a consistent visual identity that appears across every scene of every video, week after week. Your audience won't be able to tell which videos you made personally and which ones ReelForge made for you. That's not an accident.",
    },
    {
      question: "What does 'auto-post' actually mean?",
      answer:
        "When you approve your week plan, you choose how your videos publish: auto-scheduled at peak engagement times, saved as drafts for you to review first, or downloaded as MP4s so you post them yourself. The videos are already made. How and when they go live is entirely your call.",
    },
    {
      question: "Can I edit the plan before I approve it?",
      answer:
        "Yes — every topic, every hook, every format is editable before you hit Approve. The plan Claude generates is a first draft. You're the editor. Most people approve with zero changes. Some tweak a few titles. A few rebuild the whole thing. All options exist — the approval step is yours, always.",
    },
    {
      question: "What if I don't like how one of the videos came out?",
      answer:
        "If you're saving videos as drafts, you review every one before it goes public. If you're using 'Download Only' mode, you decide what gets posted. The system never publishes anything without the rules you set upfront. You're in control — you've just stopped doing the work.",
    },
    {
      question: "Is the $5 Try Out plan really one-time, no strings?",
      answer:
        "$5. One time. 7 video credits — enough for one full week of content. No subscription starts automatically. No card-on-file surprise. Use your credits whenever you're ready. It's the fastest way to see a finished, AI-generated video live on your actual channel — for the cost of a coffee.",
    },
    {
      question: "How is this different from just using ChatGPT and CapCut?",
      answer:
        "You could assemble tools yourself. You'd write prompts for every scene, generate images one by one, stitch them into video manually, sync subtitles by hand, upload to your channels, schedule the post, then do it again tomorrow. That's still hours of work per video. ReelForge isn't a better shovel. It's the whole machine — plan, generate, assemble, post — running on autopilot. There's a difference between a tool and a system.",
    },
  ],
};

// ─── Final CTA ────────────────────────────────────────────────────────────────

export const FINAL_CTA = {
  headlineLine1: "Your competitors",
  headlineLine2: "are still doing",
  headlineAccent: "it by hand.",
  headlineLine3: "Start the machine.",
  body: [
    "A full week of content, planned in 10 minutes.",
    "Generated while you sleep. Posted while you live.",
  ],
  cta: {
    label: "Start your first week — $5",
    subtext: "7 video credits · No subscription · 10 minutes to set up",
    href: "/sign-up",
  },
};

// ─── Footer ───────────────────────────────────────────────────────────────────

export const FOOTER = {
  copyright: `© ${new Date().getFullYear()} ReelForge. All rights reserved.`,
  links: [{ label: "Privacy Policy", href: "/privacy" }],
  platforms: ["Facebook Reels", "TikTok", "Instagram Reels", "YouTube Shorts"],
};
